// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadil-Tao/gopher-pay/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// TransactionRepo is an autogenerated mock type for the TransactionRepo type
type TransactionRepo struct {
	mock.Mock
}

// WriteTransaction provides a mock function with given fields: ctx, transaction, updateFn
func (_m *TransactionRepo) WriteTransaction(ctx context.Context, transaction *model.Transaction, updateFn func() error) error {
	ret := _m.Called(ctx, transaction, updateFn)

	if len(ret) == 0 {
		panic("no return value specified for WriteTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Transaction, func() error) error); ok {
		r0 = rf(ctx, transaction, updateFn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionRepo creates a new instance of TransactionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepo {
	mock := &TransactionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
