// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	model "github.com/Fadil-Tao/gopher-pay/internal/model"

	uuid "github.com/google/uuid"
)

// WalletRepo is an autogenerated mock type for the WalletRepo type
type WalletRepo struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, id, amount
func (_m *WalletRepo) Add(ctx context.Context, id uuid.UUID, amount decimal.Decimal) error {
	ret := _m.Called(ctx, id, amount)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r0 = rf(ctx, id, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWallet provides a mock function with given fields: ctx, userId
func (_m *WalletRepo) CreateWallet(ctx context.Context, userId int) error {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWalletInfoByUserId provides a mock function with given fields: ctx, userId
func (_m *WalletRepo) GetWalletInfoByUserId(ctx context.Context, userId int) (*model.Wallet, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletInfoByUserId")
	}

	var r0 *model.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*model.Wallet, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.Wallet); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletInfoByUserPhone provides a mock function with given fields: ctx, userPhone
func (_m *WalletRepo) GetWalletInfoByUserPhone(ctx context.Context, userPhone string) (*model.Wallet, error) {
	ret := _m.Called(ctx, userPhone)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletInfoByUserPhone")
	}

	var r0 *model.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Wallet, error)); ok {
		return rf(ctx, userPhone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Wallet); ok {
		r0 = rf(ctx, userPhone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userPhone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Substract provides a mock function with given fields: ctx, id, amount
func (_m *WalletRepo) Substract(ctx context.Context, id uuid.UUID, amount decimal.Decimal) error {
	ret := _m.Called(ctx, id, amount)

	if len(ret) == 0 {
		panic("no return value specified for Substract")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r0 = rf(ctx, id, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWalletRepo creates a new instance of WalletRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletRepo {
	mock := &WalletRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
