services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/gopher-pay
      - /gopher-pay/bin 
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db : 
        condition : service_healthy
    command: ["sh", "-c", "/gopher-pay/bin/migrate up && air"]
  db: 
    image: postgres:alpine
    environment:
      - POSTGRES_DB=gopherpay_db
      - POSTGRES_USER=gopherpay_user
      - POSTGRES_PASSWORD=gopherpay_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gopherpay_user -d gopherpay_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart : always  
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: